#!/usr/bin/env python3
"""Copy the canonical documents into the JavaScript the agents import.

There is no build step in this project, so a Pages Function cannot read a
file out of docs/ at runtime. The alternative to this script is pasting the
foundational model into a prompt by hand, which drifts the moment the
document is edited and nobody notices.

So: this writes functions/api/_model.js from docs/HBP-Foundational-Model.md
and records the source checksum inside it. Run with --check in CI or before
a release to find out whether the two have come apart.

    python3 scripts/sync_prompt_sources.py           # write
    python3 scripts/sync_prompt_sources.py --check   # verify only
"""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = [
    (ROOT / "docs/HBP-Foundational-Model.md", ROOT / "functions/api/_model.js", "FOUNDATIONAL_MODEL"),
]


def check_dashes(text, name):
    bad = [d for d in ("—", "–") if d in text]
    if bad:
        lines = [i + 1 for i, l in enumerate(text.splitlines()) if any(d in l for d in bad)]
        raise SystemExit(
            f"{name} contains {' and '.join(repr(d) for d in bad)} on lines {lines}. "
            "This text goes into an agent's prompt and comes back out in its voice. "
            "Fix the source document, not the generated file."
        )


def build(src, const):
    text = src.read_text(encoding="utf-8")
    check_dashes(text, src.name)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return digest, (
        f"// Generated by scripts/sync_prompt_sources.py. Do not edit.\n"
        f"// Source: {src.relative_to(ROOT)}\n"
        f"// sha256: {digest}\n"
        f"//\n"
        f"// Edit the source document and run the script again. Run it with\n"
        f"// --check to find out whether this file has fallen behind.\n\n"
        f"export const {const}_SHA = '{digest}';\n\n"
        f"export const {const} = `{escaped}`;\n"
    )


def main():
    checking = "--check" in sys.argv
    problems = []
    for src, out, const in SOURCES:
        digest, content = build(src, const)
        rel = out.relative_to(ROOT)
        if checking:
            if not out.exists():
                problems.append(f"{rel} does not exist")
            elif f"_SHA = '{digest}'" not in out.read_text(encoding="utf-8"):
                problems.append(f"{rel} is behind {src.relative_to(ROOT)}")
            else:
                print(f"  {rel} matches {src.name}")
        else:
            out.write_text(content, encoding="utf-8")
            print(f"  wrote {rel} from {src.name} ({len(content)} bytes, sha {digest[:12]})")
    if problems:
        raise SystemExit("\n".join("  " + p for p in problems) + "\n\nRun: python3 scripts/sync_prompt_sources.py")


if __name__ == "__main__":
    main()
